-- =====================================================================
--  ALLO SANTE TCHAD — donnees geographiques et services de secours
--  GENERE AUTOMATIQUEMENT par scripts/generate-geo-sql.mjs — ne pas
--  modifier a la main : editez src/data/geo.json puis relancez
--  `npm run geo:sql`.
--  A coller dans Supabase > SQL Editor apres 01_installation.sql.
--  Version des donnees : 2026-08b
-- =====================================================================

-- 1. Les 23 provinces ------------------------------------------------
insert into provinces (code, nom_fr, nom_ar, ordre) values
  ('NDJ', 'N''Djamena', 'إنجامينا', 0),
  ('BAT', 'Batha', 'البطحاء', 10),
  ('BEG', 'Bahr el Gazel', 'بحر الغزال', 20),
  ('BOR', 'Borkou', 'بوركو', 30),
  ('CHB', 'Chari-Baguirmi', 'شاري باقرمي', 40),
  ('ENE', 'Ennedi-Est', 'إنيدي الشرقية', 50),
  ('ENO', 'Ennedi-Ouest', 'إنيدي الغربية', 60),
  ('GUE', 'Guéra', 'قيرا', 70),
  ('HAL', 'Hadjer-Lamis', 'حجر لميس', 80),
  ('KAN', 'Kanem', 'كانم', 90),
  ('LAC', 'Lac', 'البحيرة', 100),
  ('LOC', 'Logone Occidental', 'لوقون الغربية', 110),
  ('LOR', 'Logone Oriental', 'لوقون الشرقية', 120),
  ('MAN', 'Mandoul', 'ماندول', 130),
  ('MKE', 'Mayo-Kebbi Est', 'مايو كبي الشرقية', 140),
  ('MKO', 'Mayo-Kebbi Ouest', 'مايو كبي الغربية', 150),
  ('MOC', 'Moyen-Chari', 'شاري الأوسط', 160),
  ('OUA', 'Ouaddaï', 'وداي', 170),
  ('SAL', 'Salamat', 'سلامات', 180),
  ('SIL', 'Sila', 'سيلا', 190),
  ('TAN', 'Tandjilé', 'تانجيلي', 200),
  ('TIB', 'Tibesti', 'تيبستي', 210),
  ('WAF', 'Wadi Fira', 'وادي فيرا', 220)
on conflict (code) do update set nom_fr = excluded.nom_fr, nom_ar = excluded.nom_ar;

-- 2. Chefs-lieux -----------------------------------------------------
insert into villes (province_id, code, nom_fr, nom_ar, chef_lieu, lat, lng) values
  ((select id from provinces where code = 'NDJ'), 'NDJ-NDJ', 'N''Djamena', 'إنجامينا', true, 12.1067, 15.0444),
  ((select id from provinces where code = 'BAT'), 'BAT-ATI', 'Ati', 'آتي', true, 13.2126, 18.3397),
  ((select id from provinces where code = 'BEG'), 'BEG-MOU', 'Moussoro', 'موسورو', true, 13.6406, 16.4908),
  ((select id from provinces where code = 'BOR'), 'BOR-FAY', 'Faya-Largeau', 'فايا لارجو', true, 17.9209, 19.0953),
  ((select id from provinces where code = 'CHB'), 'CHB-MAS', 'Massenya', 'ماسينيا', true, 11.4033, 16.1719),
  ((select id from provinces where code = 'ENE'), 'ENE-AMD', 'Am-Djarass', 'أم جرس', true, 16.0663, 22.8351),
  ((select id from provinces where code = 'ENO'), 'ENO-FAD', 'Fada', 'فادا', true, 17.1931, 21.5813),
  ((select id from provinces where code = 'GUE'), 'GUE-MON', 'Mongo', 'منقو', true, 12.1843, 18.6842),
  ((select id from provinces where code = 'HAL'), 'HAL-MSG', 'Massaguet', 'ماساقيت', true, 12.4824, 15.4396),
  ((select id from provinces where code = 'KAN'), 'KAN-MAO', 'Mao', 'ماو', true, 14.1234, 15.3108),
  ((select id from provinces where code = 'LAC'), 'LAC-BOL', 'Bol', 'بول', true, 13.4673, 14.7135),
  ((select id from provinces where code = 'LOC'), 'LOC-MDU', 'Moundou', 'موندو', true, 8.5744, 16.0772),
  ((select id from provinces where code = 'LOR'), 'LOR-DOB', 'Doba', 'دوبا', true, 8.6592, 16.8538),
  ((select id from provinces where code = 'MAN'), 'MAN-KOU', 'Koumra', 'كومرا', true, 8.9189, 17.5478),
  ((select id from provinces where code = 'MKE'), 'MKE-BON', 'Bongor', 'بنقور', true, 10.2816, 15.3713),
  ((select id from provinces where code = 'MKO'), 'MKO-PAL', 'Pala', 'بالا', true, 9.3663, 14.9097),
  ((select id from provinces where code = 'MOC'), 'MOC-SAR', 'Sarh', 'سرح', true, 9.1455, 18.3833),
  ((select id from provinces where code = 'OUA'), 'OUA-ABE', 'Abéché', 'أبشة', true, 13.8292, 20.8324),
  ((select id from provinces where code = 'SAL'), 'SAL-AMT', 'Am Timan', 'أم تيمان', true, 11.0396, 20.2826),
  ((select id from provinces where code = 'SIL'), 'SIL-GOZ', 'Goz Beïda', 'قوز بيضا', true, 12.2256, 21.4102),
  ((select id from provinces where code = 'TAN'), 'TAN-LAI', 'Laï', 'لاي', true, 9.3972, 16.3007),
  ((select id from provinces where code = 'TIB'), 'TIB-BAR', 'Bardaï', 'برداي', true, 21.355, 17.0005),
  ((select id from provinces where code = 'WAF'), 'WAF-BIL', 'Biltine', 'بلتين', true, 14.5252, 20.9287)
on conflict (code) do update set nom_fr = excluded.nom_fr, nom_ar = excluded.nom_ar, lat = excluded.lat, lng = excluded.lng;

-- 3. Quartiers (le champ qualite indique la fiabilite de la source) ---
insert into quartiers (ville_id, nom_fr, nom_ar, groupe, qualite, approuve) values
  ((select id from villes where code = 'NDJ-NDJ'), 'Farcha', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Milezi', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Madjorio', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Guilmeye', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Djougoulier', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Karkandjeri', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Amsinéné', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Massil Abcoma', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Zaraf', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Allaya', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ardeb-Timan', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Guinébor', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'N''Djamena-Koudou', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Antona', null, 1, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Djamba Ngato', null, 2, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Mardjandaffack', null, 2, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Bololo', null, 2, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Goudji', null, 2, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Klémat', null, 2, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Gardolé', null, 3, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ambassatna', null, 3, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ardep Djoumal', null, 3, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Sabangali', null, 3, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Kabalaye', null, 3, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Djambalbahr', null, 3, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Repos I', null, 4, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Repos II', null, 4, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Naga I', null, 4, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Naga II', null, 4, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Blabline', null, 4, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ridina', null, 5, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Am-Riguebé', null, 5, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Champ de Fils', null, 5, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Karkandjié', null, 5, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Moursal', null, 6, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Paris-Congo', null, 6, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Chagoua', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Dembé', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Dembé 2', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ambatta', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ambatta 2', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Boutalbagara', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Kourmanadji', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Atrone', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Amtoukoui', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Amtoukoui Alaya', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Habena', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Gassi', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Kilwiti', null, 7, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Diguel', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ndjari', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Angabo', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Zaffaye-Est', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Zaffaye-Ouest', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Machaga', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Amtoukougne Koudou', null, 8, 'wiki', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Walia', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ngoumna', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Digangali', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ngueli', null, 9, 'officiel', true)
on conflict (ville_id, nom_fr) do nothing;

insert into quartiers (ville_id, nom_fr, nom_ar, groupe, qualite, approuve) values
  ((select id from villes where code = 'NDJ-NDJ'), 'Kabé', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Toukra', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Toukra Massa', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Gardolé 2', null, 9, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Achawaïl', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Almour', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Amhalomma', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Annigueré', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Annouwara', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Dabazene', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Djabalori', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Fondoré 1', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Fondoré 2', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Goudji Charafa', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Gozator', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Hamon Kessa', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Harangadji', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Gaoui', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Hilé Houdjadj', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Lamadji', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ngabo Chaïb', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ourallah 1', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Ourallah 2', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Sadjeri', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Sadjeri-Kalatchou', null, 10, 'officiel', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Koloma', null, 0, 'local', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Tongolo', null, 0, 'local', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Mballa Toukra', null, 0, 'local', true),
  ((select id from villes where code = 'NDJ-NDJ'), 'Amriguébé', null, 0, 'local', true),
  ((select id from villes where code = 'BAT-ATI'), 'Abdjoued', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Acham', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Ambassatna', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Arabe I (Souwar Al Dahab)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Arabe II (Champ de Course)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Babal Cherif', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Bilala I (Kaskana)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Bilala II (Bab Al Rahama)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Bornou I (Abassi)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Bornou II (Al Afia)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Cherif Azawia (Albeda)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Daranaim', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Darassalam', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Djallaba I (Hilal)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Djallaba II (Nour Al Houda)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Fizane (Ridina)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Gorane (Clair)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Goz-Beida', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Hadjerai (Blabline)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Kanembou (Ryad)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Khawadjat', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Khazal Al Haye', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Kouka (Matar Al Haya)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Massalat (Chigal Fakhara)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Medego (Djabal Alnour)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Mesmedje (Babal Kher)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Ngardjana I', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Ngardjana II', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Ouaddai (Ouara)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Salamat (Bab Al Fatih)', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Sara (Nour Al Hilal)', null, null, 'etude', true)
on conflict (ville_id, nom_fr) do nothing;

insert into quartiers (ville_id, nom_fr, nom_ar, groupe, qualite, approuve) values
  ((select id from villes where code = 'BAT-ATI'), 'Wadi Djedid', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Walad Issa', null, null, 'etude', true),
  ((select id from villes where code = 'BAT-ATI'), 'Zongo', null, null, 'etude', true),
  ((select id from villes where code = 'BEG-MOU'), 'Centre', null, null, 'osm', true),
  ((select id from villes where code = 'BEG-MOU'), 'Quartier Arabe', null, null, 'osm', true),
  ((select id from villes where code = 'BEG-MOU'), 'Gourane', null, null, 'osm', true),
  ((select id from villes where code = 'BEG-MOU'), 'Sara', null, null, 'osm', true),
  ((select id from villes where code = 'BEG-MOU'), 'Ouaddaï', null, null, 'osm', true),
  ((select id from villes where code = 'BOR-FAY'), 'Centre', null, null, 'osm', true),
  ((select id from villes where code = 'BOR-FAY'), 'Housma', null, null, 'osm', true),
  ((select id from villes where code = 'BOR-FAY'), 'Djiddi', null, null, 'osm', true),
  ((select id from villes where code = 'BOR-FAY'), 'Oweney', null, null, 'osm', true),
  ((select id from villes where code = 'BOR-FAY'), 'Tchagoussou', null, null, 'osm', true),
  ((select id from villes where code = 'BOR-FAY'), 'Terre Rouge', null, null, 'presse', true),
  ((select id from villes where code = 'BOR-FAY'), 'Quartier 8', null, null, 'presse', true),
  ((select id from villes where code = 'BOR-FAY'), 'Houchouma', null, null, 'presse', true),
  ((select id from villes where code = 'GUE-MON'), 'Secteur 6', null, null, 'presse', true),
  ((select id from villes where code = 'KAN-MAO'), 'Mao Youlo', null, null, 'rapport', true),
  ((select id from villes where code = 'KAN-MAO'), 'Tchoulory', null, null, 'rapport', true),
  ((select id from villes where code = 'KAN-MAO'), 'Maïfort', null, null, 'rapport', true),
  ((select id from villes where code = 'KAN-MAO'), 'Wardari', null, null, 'rapport', true),
  ((select id from villes where code = 'KAN-MAO'), 'Koumbagri', null, null, 'rapport', true),
  ((select id from villes where code = 'KAN-MAO'), 'Youlo', null, null, 'rapport', true),
  ((select id from villes where code = 'LAC-BOL'), 'Walabari', null, null, 'presse', true),
  ((select id from villes where code = 'LOC-MDU'), 'Dombao', null, 1, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Doyon', null, 1, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Taye', null, 1, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Bebandji', null, 1, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Koudjiriko', null, 1, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Ngara', null, 1, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Nguelbe', null, 2, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Baguirmi', null, 2, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Bournou', null, 2, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Haoussa', null, 2, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Guelkoura', null, 3, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Quinze Ans', null, 3, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Doumbeur I', null, 3, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Doheri', null, 3, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Mbague', null, 3, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Mbombaya', null, 4, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Gueldjem', null, 4, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Doumbeur II', null, 4, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Koutou Guelmbague', null, 4, 'wiki', true),
  ((select id from villes where code = 'LOC-MDU'), 'Madana', null, 4, 'wiki', true),
  ((select id from villes where code = 'LOR-DOB'), 'Doba Ndoh', null, 1, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Doba Mbaye', null, 1, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Doba Ya', null, 1, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Mission Catholique', null, 1, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Gaki (Ngounwéte)', null, 1, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Guidikou', null, 1, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Haoussa', null, 2, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Bornou', null, 2, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Arabe', null, 2, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Baguirmi', null, 2, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Divers', null, 2, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Témbi', null, 3, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Takasna', null, 3, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Wémbeundoubeu', null, 3, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Forgeron', null, 3, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Bédogo', null, 3, 'etude', true)
on conflict (ville_id, nom_fr) do nothing;

insert into quartiers (ville_id, nom_fr, nom_ar, groupe, qualite, approuve) values
  ((select id from villes where code = 'LOR-DOB'), 'Bédokassa', null, 3, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Wédoli', null, 3, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Coton Tchad', null, 4, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Béraba', null, 4, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Maïhongo', null, 4, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Yeuldanoum', null, 4, 'etude', true),
  ((select id from villes where code = 'LOR-DOB'), 'Ndoubeu-aéroport', null, 4, 'etude', true),
  ((select id from villes where code = 'MAN-KOU'), 'Baguirmi', null, null, 'osm', true),
  ((select id from villes where code = 'MAN-KOU'), 'Bornou', null, null, 'osm', true),
  ((select id from villes where code = 'MAN-KOU'), 'Goulaye', null, null, 'osm', true),
  ((select id from villes where code = 'MAN-KOU'), 'Bénodjo', null, null, 'osm', true),
  ((select id from villes where code = 'MAN-KOU'), 'Londih', null, null, 'presse', true),
  ((select id from villes where code = 'MKE-BON'), 'Ardeb', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Bongor Siéke', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Commerçant', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Darkaweye', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Djambalbar', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Djoh-Bongor', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Fordamba', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Golongtougou', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Gouloumoun-Bassi', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Lama-Lama', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Largeau', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Mailao', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Raouna', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Silé 1', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Silé 2', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Miogoye Blah', null, null, 'etude', true),
  ((select id from villes where code = 'MKE-BON'), 'Djamboutou', null, null, 'etude', true),
  ((select id from villes where code = 'MKO-PAL'), 'Coton Tchad', null, 1, 'presse', true),
  ((select id from villes where code = 'MKO-PAL'), 'EGTH', null, 1, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Résidentiel', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Maye', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Sara Kaba', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Niellim', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Baguirmi', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Bégou', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Blablim', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Blablim Nord', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Bornou', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Haoussa', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Kassaye', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Kassaye Sud', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Paris Congo', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Paris Congo Sud', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Paris Sara', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Quinze Ans', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Maingara', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Mbaimandja', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Yalnas', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Maroc', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Kamati', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Jardin', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Kemkian', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Banda', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Gardolé', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Tatala', null, null, 'presse', true),
  ((select id from villes where code = 'MOC-SAR'), 'Tombalbaye', null, null, 'presse', true),
  ((select id from villes where code = 'OUA-ABE'), 'Moumié', null, null, 'osm', true),
  ((select id from villes where code = 'OUA-ABE'), 'Taradona', null, null, 'etude', true)
on conflict (ville_id, nom_fr) do nothing;

insert into quartiers (ville_id, nom_fr, nom_ar, groupe, qualite, approuve) values
  ((select id from villes where code = 'OUA-ABE'), 'Amsiego', null, null, 'osm', true),
  ((select id from villes where code = 'OUA-ABE'), 'Amsoudourié', null, null, 'osm', true),
  ((select id from villes where code = 'OUA-ABE'), 'Ahmat Al Badwi', null, null, 'osm', true),
  ((select id from villes where code = 'OUA-ABE'), 'Salamat', null, null, 'etude', true),
  ((select id from villes where code = 'OUA-ABE'), 'Agad-Mahamit', null, null, 'etude', true),
  ((select id from villes where code = 'OUA-ABE'), 'Agarachid Dakhalani', null, null, 'osm', true),
  ((select id from villes where code = 'OUA-ABE'), 'Kamina Hayalmatar', null, null, 'presse', true),
  ((select id from villes where code = 'OUA-ABE'), 'Djatinié', null, null, 'presse', true),
  ((select id from villes where code = 'SAL-AMT'), 'Adjabona', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Am-Fondok', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Commerçant', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Dar Al Salam 1', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Djambal-Barh', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Gardolé', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Quartier Administratif', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Riad', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Taradona 2', null, null, 'osm', true),
  ((select id from villes where code = 'SAL-AMT'), 'Zongo', null, null, 'osm', true),
  ((select id from villes where code = 'TAN-LAI'), 'Nougou', null, null, 'presse', true),
  ((select id from villes where code = 'TAN-LAI'), 'Taba', null, null, 'presse', true),
  ((select id from villes where code = 'TAN-LAI'), 'Tagbian', null, null, 'presse', true),
  ((select id from villes where code = 'TAN-LAI'), 'Dokmayo', null, null, 'presse', true),
  ((select id from villes where code = 'TAN-LAI'), '15 ans', null, null, 'presse', true),
  ((select id from villes where code = 'TAN-LAI'), 'Mailoa', null, null, 'presse', true)
on conflict (ville_id, nom_fr) do nothing;

-- 4. Services de secours pre-crees pour chaque chef-lieu -------------
--    Ils sont visibles immediatement. Ceux dont le numero est inconnu
--    apparaissent avec la mention "numero a completer" et remontent dans
--    le back-office (Admin > Secours > numeros manquants).
insert into professionnels
  (province_id, ville_id, type, nom, specialite, telephone, statut, service_officiel, numero_confirme, lat, lng, horaires)
values
  ((select id from provinces where code = 'NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   'police'::type_pro, 'Commissariat de police de N''Djamena', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.1067, 15.0444, '24h/24'),
  ((select id from provinces where code = 'NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de N''Djamena', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.1067, 15.0444, '24h/24'),
  ((select id from provinces where code = 'NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de N''Djamena', 'Service de secours',
   '+23522522555', 'verifie'::statut_pro, true, false, 12.1067, 15.0444, '24h/24'),
  ((select id from provinces where code = 'BAT'),
   (select id from villes where code = 'BAT-ATI'),
   'police'::type_pro, 'Commissariat de police de Ati', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.2126, 18.3397, '24h/24'),
  ((select id from provinces where code = 'BAT'),
   (select id from villes where code = 'BAT-ATI'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Ati', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.2126, 18.3397, '24h/24'),
  ((select id from provinces where code = 'BAT'),
   (select id from villes where code = 'BAT-ATI'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Ati', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.2126, 18.3397, '24h/24'),
  ((select id from provinces where code = 'BEG'),
   (select id from villes where code = 'BEG-MOU'),
   'police'::type_pro, 'Commissariat de police de Moussoro', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.6406, 16.4908, '24h/24'),
  ((select id from provinces where code = 'BEG'),
   (select id from villes where code = 'BEG-MOU'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Moussoro', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.6406, 16.4908, '24h/24'),
  ((select id from provinces where code = 'BEG'),
   (select id from villes where code = 'BEG-MOU'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Moussoro', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.6406, 16.4908, '24h/24'),
  ((select id from provinces where code = 'BOR'),
   (select id from villes where code = 'BOR-FAY'),
   'police'::type_pro, 'Commissariat de police de Faya-Largeau', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 17.9209, 19.0953, '24h/24'),
  ((select id from provinces where code = 'BOR'),
   (select id from villes where code = 'BOR-FAY'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Faya-Largeau', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 17.9209, 19.0953, '24h/24'),
  ((select id from provinces where code = 'BOR'),
   (select id from villes where code = 'BOR-FAY'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Faya-Largeau', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 17.9209, 19.0953, '24h/24'),
  ((select id from provinces where code = 'CHB'),
   (select id from villes where code = 'CHB-MAS'),
   'police'::type_pro, 'Commissariat de police de Massenya', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 11.4033, 16.1719, '24h/24'),
  ((select id from provinces where code = 'CHB'),
   (select id from villes where code = 'CHB-MAS'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Massenya', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 11.4033, 16.1719, '24h/24'),
  ((select id from provinces where code = 'CHB'),
   (select id from villes where code = 'CHB-MAS'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Massenya', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 11.4033, 16.1719, '24h/24'),
  ((select id from provinces where code = 'ENE'),
   (select id from villes where code = 'ENE-AMD'),
   'police'::type_pro, 'Commissariat de police de Am-Djarass', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 16.0663, 22.8351, '24h/24'),
  ((select id from provinces where code = 'ENE'),
   (select id from villes where code = 'ENE-AMD'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Am-Djarass', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 16.0663, 22.8351, '24h/24'),
  ((select id from provinces where code = 'ENE'),
   (select id from villes where code = 'ENE-AMD'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Am-Djarass', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 16.0663, 22.8351, '24h/24'),
  ((select id from provinces where code = 'ENO'),
   (select id from villes where code = 'ENO-FAD'),
   'police'::type_pro, 'Commissariat de police de Fada', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 17.1931, 21.5813, '24h/24'),
  ((select id from provinces where code = 'ENO'),
   (select id from villes where code = 'ENO-FAD'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Fada', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 17.1931, 21.5813, '24h/24'),
  ((select id from provinces where code = 'ENO'),
   (select id from villes where code = 'ENO-FAD'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Fada', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 17.1931, 21.5813, '24h/24'),
  ((select id from provinces where code = 'GUE'),
   (select id from villes where code = 'GUE-MON'),
   'police'::type_pro, 'Commissariat de police de Mongo', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.1843, 18.6842, '24h/24'),
  ((select id from provinces where code = 'GUE'),
   (select id from villes where code = 'GUE-MON'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Mongo', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.1843, 18.6842, '24h/24'),
  ((select id from provinces where code = 'GUE'),
   (select id from villes where code = 'GUE-MON'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Mongo', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.1843, 18.6842, '24h/24'),
  ((select id from provinces where code = 'HAL'),
   (select id from villes where code = 'HAL-MSG'),
   'police'::type_pro, 'Commissariat de police de Massaguet', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.4824, 15.4396, '24h/24'),
  ((select id from provinces where code = 'HAL'),
   (select id from villes where code = 'HAL-MSG'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Massaguet', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.4824, 15.4396, '24h/24'),
  ((select id from provinces where code = 'HAL'),
   (select id from villes where code = 'HAL-MSG'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Massaguet', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.4824, 15.4396, '24h/24'),
  ((select id from provinces where code = 'KAN'),
   (select id from villes where code = 'KAN-MAO'),
   'police'::type_pro, 'Commissariat de police de Mao', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 14.1234, 15.3108, '24h/24'),
  ((select id from provinces where code = 'KAN'),
   (select id from villes where code = 'KAN-MAO'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Mao', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 14.1234, 15.3108, '24h/24'),
  ((select id from provinces where code = 'KAN'),
   (select id from villes where code = 'KAN-MAO'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Mao', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 14.1234, 15.3108, '24h/24'),
  ((select id from provinces where code = 'LAC'),
   (select id from villes where code = 'LAC-BOL'),
   'police'::type_pro, 'Commissariat de police de Bol', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.4673, 14.7135, '24h/24'),
  ((select id from provinces where code = 'LAC'),
   (select id from villes where code = 'LAC-BOL'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Bol', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.4673, 14.7135, '24h/24'),
  ((select id from provinces where code = 'LAC'),
   (select id from villes where code = 'LAC-BOL'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Bol', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.4673, 14.7135, '24h/24'),
  ((select id from provinces where code = 'LOC'),
   (select id from villes where code = 'LOC-MDU'),
   'police'::type_pro, 'Commissariat de police de Moundou', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.5744, 16.0772, '24h/24'),
  ((select id from provinces where code = 'LOC'),
   (select id from villes where code = 'LOC-MDU'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Moundou', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.5744, 16.0772, '24h/24'),
  ((select id from provinces where code = 'LOC'),
   (select id from villes where code = 'LOC-MDU'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Moundou', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.5744, 16.0772, '24h/24'),
  ((select id from provinces where code = 'LOR'),
   (select id from villes where code = 'LOR-DOB'),
   'police'::type_pro, 'Commissariat de police de Doba', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.6592, 16.8538, '24h/24'),
  ((select id from provinces where code = 'LOR'),
   (select id from villes where code = 'LOR-DOB'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Doba', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.6592, 16.8538, '24h/24'),
  ((select id from provinces where code = 'LOR'),
   (select id from villes where code = 'LOR-DOB'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Doba', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.6592, 16.8538, '24h/24'),
  ((select id from provinces where code = 'MAN'),
   (select id from villes where code = 'MAN-KOU'),
   'police'::type_pro, 'Commissariat de police de Koumra', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.9189, 17.5478, '24h/24'),
  ((select id from provinces where code = 'MAN'),
   (select id from villes where code = 'MAN-KOU'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Koumra', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.9189, 17.5478, '24h/24'),
  ((select id from provinces where code = 'MAN'),
   (select id from villes where code = 'MAN-KOU'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Koumra', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 8.9189, 17.5478, '24h/24'),
  ((select id from provinces where code = 'MKE'),
   (select id from villes where code = 'MKE-BON'),
   'police'::type_pro, 'Commissariat de police de Bongor', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 10.2816, 15.3713, '24h/24'),
  ((select id from provinces where code = 'MKE'),
   (select id from villes where code = 'MKE-BON'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Bongor', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 10.2816, 15.3713, '24h/24'),
  ((select id from provinces where code = 'MKE'),
   (select id from villes where code = 'MKE-BON'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Bongor', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 10.2816, 15.3713, '24h/24'),
  ((select id from provinces where code = 'MKO'),
   (select id from villes where code = 'MKO-PAL'),
   'police'::type_pro, 'Commissariat de police de Pala', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.3663, 14.9097, '24h/24'),
  ((select id from provinces where code = 'MKO'),
   (select id from villes where code = 'MKO-PAL'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Pala', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.3663, 14.9097, '24h/24'),
  ((select id from provinces where code = 'MKO'),
   (select id from villes where code = 'MKO-PAL'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Pala', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.3663, 14.9097, '24h/24'),
  ((select id from provinces where code = 'MOC'),
   (select id from villes where code = 'MOC-SAR'),
   'police'::type_pro, 'Commissariat de police de Sarh', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.1455, 18.3833, '24h/24'),
  ((select id from provinces where code = 'MOC'),
   (select id from villes where code = 'MOC-SAR'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Sarh', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.1455, 18.3833, '24h/24'),
  ((select id from provinces where code = 'MOC'),
   (select id from villes where code = 'MOC-SAR'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Sarh', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.1455, 18.3833, '24h/24'),
  ((select id from provinces where code = 'OUA'),
   (select id from villes where code = 'OUA-ABE'),
   'police'::type_pro, 'Commissariat de police de Abéché', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.8292, 20.8324, '24h/24'),
  ((select id from provinces where code = 'OUA'),
   (select id from villes where code = 'OUA-ABE'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Abéché', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.8292, 20.8324, '24h/24'),
  ((select id from provinces where code = 'OUA'),
   (select id from villes where code = 'OUA-ABE'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Abéché', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 13.8292, 20.8324, '24h/24'),
  ((select id from provinces where code = 'SAL'),
   (select id from villes where code = 'SAL-AMT'),
   'police'::type_pro, 'Commissariat de police de Am Timan', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 11.0396, 20.2826, '24h/24'),
  ((select id from provinces where code = 'SAL'),
   (select id from villes where code = 'SAL-AMT'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Am Timan', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 11.0396, 20.2826, '24h/24'),
  ((select id from provinces where code = 'SAL'),
   (select id from villes where code = 'SAL-AMT'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Am Timan', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 11.0396, 20.2826, '24h/24'),
  ((select id from provinces where code = 'SIL'),
   (select id from villes where code = 'SIL-GOZ'),
   'police'::type_pro, 'Commissariat de police de Goz Beïda', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.2256, 21.4102, '24h/24'),
  ((select id from provinces where code = 'SIL'),
   (select id from villes where code = 'SIL-GOZ'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Goz Beïda', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.2256, 21.4102, '24h/24'),
  ((select id from provinces where code = 'SIL'),
   (select id from villes where code = 'SIL-GOZ'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Goz Beïda', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 12.2256, 21.4102, '24h/24'),
  ((select id from provinces where code = 'TAN'),
   (select id from villes where code = 'TAN-LAI'),
   'police'::type_pro, 'Commissariat de police de Laï', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.3972, 16.3007, '24h/24'),
  ((select id from provinces where code = 'TAN'),
   (select id from villes where code = 'TAN-LAI'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Laï', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.3972, 16.3007, '24h/24'),
  ((select id from provinces where code = 'TAN'),
   (select id from villes where code = 'TAN-LAI'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Laï', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 9.3972, 16.3007, '24h/24'),
  ((select id from provinces where code = 'TIB'),
   (select id from villes where code = 'TIB-BAR'),
   'police'::type_pro, 'Commissariat de police de Bardaï', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 21.355, 17.0005, '24h/24'),
  ((select id from provinces where code = 'TIB'),
   (select id from villes where code = 'TIB-BAR'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Bardaï', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 21.355, 17.0005, '24h/24'),
  ((select id from provinces where code = 'TIB'),
   (select id from villes where code = 'TIB-BAR'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Bardaï', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 21.355, 17.0005, '24h/24'),
  ((select id from provinces where code = 'WAF'),
   (select id from villes where code = 'WAF-BIL'),
   'police'::type_pro, 'Commissariat de police de Biltine', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 14.5252, 20.9287, '24h/24'),
  ((select id from provinces where code = 'WAF'),
   (select id from villes where code = 'WAF-BIL'),
   'gendarmerie'::type_pro, 'Brigade de gendarmerie de Biltine', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 14.5252, 20.9287, '24h/24'),
  ((select id from provinces where code = 'WAF'),
   (select id from villes where code = 'WAF-BIL'),
   'pompiers'::type_pro, 'Sapeurs-pompiers de Biltine', 'Service de secours',
   null, 'verifie'::statut_pro, true, false, 14.5252, 20.9287, '24h/24')
on conflict do nothing;

-- 5. Numeros d'urgence affiches en bandeau ---------------------------
--    ATTENTION : les entrees "verifie = false" proviennent de sources qui
--    se contredisent. Testez-les depuis un telephone tchadien (Airtel ET
--    Moov) avant la mise en production, puis passez-les a true depuis
--    Admin > Numeros d'urgence.
insert into numeros_urgence (libelle_fr, libelle_ar, tel, tel2, ville_id, national, h24, verifie, source, ordre) values
  ('CHU de la Mère et de l''Enfant — urgences', 'المستشفى الجامعي للأم والطفل — الطوارئ', '+23563077760', null, (select id from villes where nom_fr = 'N''Djamena' limit 1), false, true, true, 'Site officiel de l''etablissement (chume-ndjamena.com)', 0),
  ('CHU La Renaissance — urgences', 'المستشفى الجامعي النهضة — الطوارئ', '+23566972260', '+23522532090', (select id from villes where nom_fr = 'N''Djamena' limit 1), false, true, true, 'Site officiel + France Diplomatie', 10),
  ('CHU Le Bon Samaritain', 'المستشفى الجامعي السامري الصالح', '+23566366644', '+23590485347', (select id from villes where nom_fr = 'N''Djamena' limit 1), false, false, true, 'Site officiel (chu-lebonsamaritain.org)', 20),
  ('SOS International — assistance 24h/24', 'إس أو إس الدولية — مساعدة 24/24', '+23522522501', null, (select id from villes where nom_fr = 'N''Djamena' limit 1), false, true, true, 'France Diplomatie — Tchad, contacts utiles', 30),
  ('Police (numéro court)', 'الشرطة (رقم قصير)', '17', null, null, true, true, false, 'Agregateurs internationaux — NON confirme par une source tchadienne officielle', 40),
  ('Sapeurs-pompiers (numéro court)', 'الإطفاء (رقم قصير)', '18', null, null, true, true, false, 'Agregateurs + site de la commune du 1er arrondissement de N''Djamena', 50),
  ('Sapeurs-pompiers N''Djamena (standard)', 'الإطفاء إنجامينا', '+23522522555', null, (select id from villes where nom_fr = 'N''Djamena' limit 1), false, true, false, 'Annonce de la Mairie de N''Djamena reprise par la presse (2021) — a retester', 60),
  ('Numéro vert santé (Ministère de la Santé)', 'الرقم الأخضر للصحة', '1313', null, null, true, true, false, 'Cree en 2020 (call-center ARCEP) — activite actuelle non confirmee', 70)
on conflict do nothing;

-- 6. Hopitaux de reference (affiches en cas d'escalade) --------------
insert into professionnels
  (province_id, ville_id, type, nom, specialite, telephone, statut, service_officiel, numero_confirme, horaires)
values
  ((select province_id from villes where nom_fr = 'N''Djamena' limit 1),
   (select id from villes where nom_fr = 'N''Djamena' limit 1),
   'centre_sante'::type_pro, 'Hôpital Général de Référence Nationale (HGRN)', 'Hôpital de référence', '+23522514361',
   'verifie'::statut_pro, true, false, '24h/24'),
  ((select province_id from villes where nom_fr = 'N''Djamena' limit 1),
   (select id from villes where nom_fr = 'N''Djamena' limit 1),
   'centre_sante'::type_pro, 'Hôpital de l''Amitié Tchad-Chine', 'Hôpital de référence', null,
   'verifie'::statut_pro, true, false, '24h/24'),
  ((select province_id from villes where nom_fr = 'Moundou' limit 1),
   (select id from villes where nom_fr = 'Moundou' limit 1),
   'centre_sante'::type_pro, 'Hôpital Provincial de Moundou', 'Hôpital de référence', null,
   'verifie'::statut_pro, true, false, '24h/24'),
  ((select province_id from villes where nom_fr = 'Sarh' limit 1),
   (select id from villes where nom_fr = 'Sarh' limit 1),
   'centre_sante'::type_pro, 'Hôpital Provincial de Sarh', 'Hôpital de référence', null,
   'verifie'::statut_pro, true, false, '24h/24'),
  ((select province_id from villes where nom_fr = 'Abéché' limit 1),
   (select id from villes where nom_fr = 'Abéché' limit 1),
   'centre_sante'::type_pro, 'CHU d''Abéché', 'Hôpital de référence', null,
   'verifie'::statut_pro, true, false, '24h/24')
on conflict do nothing;

select
  (select count(*) from provinces)      as provinces,
  (select count(*) from villes)         as villes,
  (select count(*) from quartiers)      as quartiers,
  (select count(*) from professionnels where service_officiel) as services_secours,
  (select count(*) from numeros_urgence) as numeros,
  'Etape 2/3 terminee. Facultatif : 03_donnees_demo.sql' as resultat;
