-- =====================================================================
--  ALLO SANTE TCHAD — jeu de donnees de DEMONSTRATION (facultatif)
--  GENERE AUTOMATIQUEMENT — ne pas modifier a la main.
--
--  Jeu de donnees FICTIF, destine a la demonstration. Aucun de ces professionnels n'existe et aucun numero n'est reel : les fiches marquees demo n'ouvrent jamais un appel. A supprimer avant la mise en production (bouton dedie dans le back-office).
--
--  Pour tout effacer d'un coup : lancez 04_effacer_demo.sql
-- =====================================================================

insert into professionnels
  (type, nom, specialite, province_id, ville_id, quartier_id, horaires,
   en_ligne, derniere_activite, statut, demo, numero_confirme, telephone, lat, lng)
values
  ('medecin'::type_pro, 'Dr Hassane Abakar (DÉMO)', 'Médecine générale',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Moursal' limit 1),
   'Lun–Sam 8h–19h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('medecin'::type_pro, 'Dr Fatimé Ngaba (DÉMO)', 'Pédiatrie',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Chagoua' limit 1),
   'Lun–Ven 9h–17h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('medecin'::type_pro, 'Dr Mahamat Saleh Djibrine (DÉMO)', 'Chirurgie / traumatologie',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Klémat' limit 1),
   'Astreinte 24h/24', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('medecin'::type_pro, 'Dr Achta Oumar (DÉMO)', 'Gynécologie-obstétrique',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Farcha' limit 1),
   'Lun–Sam 8h–16h', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('medecin'::type_pro, 'Dr Djimet Ngarhoulem (DÉMO)', 'Médecine interne',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Diguel' limit 1),
   'Lun–Ven 8h–15h', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('infirmier'::type_pro, 'Brahim Adoum (DÉMO)', 'Soins à domicile, pansements, perfusions',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Dembé' limit 1),
   'Tous les jours 7h–21h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('infirmier'::type_pro, 'Mariam Hissein (DÉMO)', 'Soins infirmiers, injections',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Walia' limit 1),
   'Lun–Sam 8h–20h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('infirmier'::type_pro, 'Abdelkerim Tidjani (DÉMO)', 'Urgences, premiers secours',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Gassi' limit 1),
   '24h/24', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('sage_femme'::type_pro, 'Zara Mahamat (DÉMO)', 'Accouchement, suivi de grossesse',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Ndjari' limit 1),
   '24h/24', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('sage_femme'::type_pro, 'Halimé Youssouf (DÉMO)', 'Suivi de grossesse, consultations prénatales',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Toukra' limit 1),
   'Lun–Sam 8h–18h', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('pharmacie'::type_pro, 'Pharmacie du Rond-Point (DÉMO)', 'Pharmacie de garde le week-end',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Sabangali' limit 1),
   '8h–22h, garde le dimanche', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('pharmacie'::type_pro, 'Pharmacie Al Amal (DÉMO)', 'Pharmacie',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Moursal' limit 1),
   '8h–20h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('pharmacie'::type_pro, 'Pharmacie de Chagoua (DÉMO)', 'Pharmacie, livraison moto-taxi',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Chagoua' limit 1),
   '7h30–21h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('pharmacie'::type_pro, 'Pharmacie Walia Santé (DÉMO)', 'Pharmacie',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Walia' limit 1),
   '8h–19h', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('centre_sante'::type_pro, 'Centre de santé de Farcha (DÉMO)', 'Consultations, vaccinations, maternité',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Farcha' limit 1),
   '24h/24', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('centre_sante'::type_pro, 'Clinique du Fleuve (DÉMO)', 'Urgences, imagerie, laboratoire',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Klémat' limit 1),
   '24h/24', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('centre_sante'::type_pro, 'Centre de santé de Diguel (DÉMO)', 'Consultations, soins courants',
   (select province_id from villes where code = 'NDJ-NDJ'),
   (select id from villes where code = 'NDJ-NDJ'),
   (select id from quartiers where ville_id = (select id from villes where code = 'NDJ-NDJ') and nom_fr = 'Diguel' limit 1),
   '7h–19h', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'NDJ-NDJ'),
   (select lng from villes where code = 'NDJ-NDJ')),
  ('medecin'::type_pro, 'Dr Nadjita Beindé (DÉMO)', 'Médecine générale',
   (select province_id from villes where code = 'LOC-MDU'),
   (select id from villes where code = 'LOC-MDU'),
   (select id from quartiers where ville_id = (select id from villes where code = 'LOC-MDU') and nom_fr = 'Doyon' limit 1),
   'Lun–Sam 8h–18h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'LOC-MDU'),
   (select lng from villes where code = 'LOC-MDU')),
  ('infirmier'::type_pro, 'Rimtebaye Ngonde (DÉMO)', 'Soins à domicile',
   (select province_id from villes where code = 'LOC-MDU'),
   (select id from villes where code = 'LOC-MDU'),
   (select id from quartiers where ville_id = (select id from villes where code = 'LOC-MDU') and nom_fr = 'Baguirmi' limit 1),
   '7h–20h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'LOC-MDU'),
   (select lng from villes where code = 'LOC-MDU')),
  ('pharmacie'::type_pro, 'Pharmacie de Moundou Centre (DÉMO)', 'Pharmacie',
   (select province_id from villes where code = 'LOC-MDU'),
   (select id from villes where code = 'LOC-MDU'),
   (select id from quartiers where ville_id = (select id from villes where code = 'LOC-MDU') and nom_fr = 'Guelkoura' limit 1),
   '8h–20h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'LOC-MDU'),
   (select lng from villes where code = 'LOC-MDU')),
  ('centre_sante'::type_pro, 'Centre de santé de Mbombaya (DÉMO)', 'Consultations, maternité',
   (select province_id from villes where code = 'LOC-MDU'),
   (select id from villes where code = 'LOC-MDU'),
   (select id from quartiers where ville_id = (select id from villes where code = 'LOC-MDU') and nom_fr = 'Mbombaya' limit 1),
   '24h/24', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'LOC-MDU'),
   (select lng from villes where code = 'LOC-MDU')),
  ('medecin'::type_pro, 'Dr Koumadji Ndoubalengar (DÉMO)', 'Médecine générale',
   (select province_id from villes where code = 'MOC-SAR'),
   (select id from villes where code = 'MOC-SAR'),
   (select id from quartiers where ville_id = (select id from villes where code = 'MOC-SAR') and nom_fr = 'Résidentiel' limit 1),
   'Lun–Ven 8h–17h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'MOC-SAR'),
   (select lng from villes where code = 'MOC-SAR')),
  ('sage_femme'::type_pro, 'Madeleine Nadjilem (DÉMO)', 'Accouchement',
   (select province_id from villes where code = 'MOC-SAR'),
   (select id from villes where code = 'MOC-SAR'),
   (select id from quartiers where ville_id = (select id from villes where code = 'MOC-SAR') and nom_fr = 'Kassaye' limit 1),
   '24h/24', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'MOC-SAR'),
   (select lng from villes where code = 'MOC-SAR')),
  ('pharmacie'::type_pro, 'Pharmacie du Chari (DÉMO)', 'Pharmacie',
   (select province_id from villes where code = 'MOC-SAR'),
   (select id from villes where code = 'MOC-SAR'),
   (select id from quartiers where ville_id = (select id from villes where code = 'MOC-SAR') and nom_fr = 'Bégou' limit 1),
   '8h–19h30', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'MOC-SAR'),
   (select lng from villes where code = 'MOC-SAR')),
  ('centre_sante'::type_pro, 'Centre de santé de Bégou (DÉMO)', 'Soins courants, vaccinations',
   (select province_id from villes where code = 'MOC-SAR'),
   (select id from villes where code = 'MOC-SAR'),
   (select id from quartiers where ville_id = (select id from villes where code = 'MOC-SAR') and nom_fr = 'Bégou' limit 1),
   '7h–18h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'MOC-SAR'),
   (select lng from villes where code = 'MOC-SAR')),
  ('medecin'::type_pro, 'Dr Idriss Al-Hadj (DÉMO)', 'Médecine générale',
   (select province_id from villes where code = 'OUA-ABE'),
   (select id from villes where code = 'OUA-ABE'),
   (select id from quartiers where ville_id = (select id from villes where code = 'OUA-ABE') and nom_fr = 'Moumié' limit 1),
   'Lun–Sam 8h–18h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'OUA-ABE'),
   (select lng from villes where code = 'OUA-ABE')),
  ('infirmier'::type_pro, 'Amina Souleymane (DÉMO)', 'Soins infirmiers',
   (select province_id from villes where code = 'OUA-ABE'),
   (select id from villes where code = 'OUA-ABE'),
   (select id from quartiers where ville_id = (select id from villes where code = 'OUA-ABE') and nom_fr = 'Taradona' limit 1),
   '8h–20h', false, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'OUA-ABE'),
   (select lng from villes where code = 'OUA-ABE')),
  ('pharmacie'::type_pro, 'Pharmacie d''Abéché (DÉMO)', 'Pharmacie, garde de nuit',
   (select province_id from villes where code = 'OUA-ABE'),
   (select id from villes where code = 'OUA-ABE'),
   (select id from quartiers where ville_id = (select id from villes where code = 'OUA-ABE') and nom_fr = 'Moumié' limit 1),
   '8h–22h', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'OUA-ABE'),
   (select lng from villes where code = 'OUA-ABE')),
  ('centre_sante'::type_pro, 'Centre de santé d''Amsiego (DÉMO)', 'Consultations, maternité',
   (select province_id from villes where code = 'OUA-ABE'),
   (select id from villes where code = 'OUA-ABE'),
   (select id from quartiers where ville_id = (select id from villes where code = 'OUA-ABE') and nom_fr = 'Amsiego' limit 1),
   '24h/24', true, now(), 'verifie'::statut_pro, true, false, null,
   (select lat from villes where code = 'OUA-ABE'),
   (select lng from villes where code = 'OUA-ABE'))
on conflict do nothing;

select count(*) as fiches_demo, 'Jeu de demonstration installe.' as resultat
from professionnels where demo;
